source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.13'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.2'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
    gem 'curate', :path=>'../../../curate'
    gem 'kaminari', github: 'harai/kaminari', branch: 'route_prefix_prototype'
    gem 'browse-everything'
    gem 'hydra-head', github: 'ndlib/hydra-head', branch: 'fix-curate-travis'

    group :test do
      gem 'rspec-rails', '~> 3.0.2'
      gem 'capybara', '2.4.1'
      gem 'coveralls', require: false
      gem 'database_cleaner', '< 1.1.0'
      gem 'factory_girl_rails', '~> 4.2.0'
      gem 'launchy'
      gem 'poltergeist'
      gem 'rspec-html-matchers', '~> 0.6.1'
      gem 'rspec-its', '~> 1.0.1'
      gem 'rspec-given'
      gem 'rspec-activemodel-mocks'
      gem 'simplecov', require: false
      gem 'test_after_commit'
      gem 'timecop'
      gem 'vcr'
      gem 'webmock'
    end
gem 'byebug'

gem "bootstrap-sass"
gem "devise"
gem "devise-guests", "~> 0.3"
group :development, :test do
  gem "rspec-rails", "~> 3.0.2"
  gem "jettywrapper"
end
