---
file_system:
  :home: /Users/blakshmi/projects/ndlib/curate/spec/support
box:
  :client_id: <your client id>
  :client_secret: <your client secret>
drop_box:
  :app_key: <your client id>
  :app_secret: <your app secret>
google_drive:
  :client_id: <your client id>
  :client_secret: <your client secret>
