departments:
  AME: 'Aerospace and Mechanical Engineering'
  ANTH: 'Anthropology'
  ACMS: 'Applied and Computational Mathematics and Statistics'
  ART: 'Art, Art History and Design'
  BIOE: 'Bioengineering'
  BIOS: 'Biological Sciences'
  CBE: 'Chemical and Biomolecular Engineering'
  CHEG: 'Chemical and Biomolecular Engineering'
  'Civil Engineering and Geological Science': 'Civil and Environmental Engineering and Earth Sciences'
  CEEES: 'Civil and Environmental Engineering and Earth Sciences'
  CEGS: 'Civil and Environmental Engineering and Earth Sciences'
  CHEM: 'Chemistry'
  CLAS: 'Classics'
  CSE: 'Computer Science and Engineering'
  CW: 'Creative Writing'
  ENGL-CW: 'Creative Writing'
  'Economics and Econometrics': 'Economics'
  ECON: 'Economics'
  EE: 'Electrical Engineering'
  ENGL: 'English'
  ECS: 'Early Christian Studies'
  HIST: 'History'
  HIPS: 'History and Philosophy of Science'
  IBMS: 'Integrated Biomedical Sciences'
  PEACE: 'Peace Studies'
  IIPS: 'Peace Studies'
  Law: 'Law'
  'PhD in Literature': 'Literature'
  LIT: 'Literature'
  MATH: 'Mathematics'
  'Medieval Institute': 'Medieval Studies'
  MI: 'Medieval Studies'
  MS: 'Medieval Studies'
  PIL: 'Philosophy'
  PHYS: 'Physics'
  POLS: 'Political Science'
  PSY: 'Psychology'
  ROML: 'Romance Languages and Literatures'
  SACM: 'Sacred Music'
  SOC: 'Sociology'
  THEO: 'Theology'
